### ISSUE TITLE
Messages out of order

### ISSUE THREAD

**Issue by jeanlucthumm** [isamert/scli#105] opened 2021-03-04 03:01 UTC
While having a conversation on scli it seems like all my friends messages appear on the left, and all my messages appear on the right: 
```
>> msg from friend
>> msg from friend 2
<-------- incoming messages pile up here
                                                                             response from me ✓✓
                                                                             response from me ✓✓
                                            my messages pile up here -------------------->
```
Normally with messaging apps it goes back and forth as the conversation progresses. Is this a feature or a bug?

Also note that if I go to the signal desktop app, for example, and continue the conversation there, then when scli refreshes it does bring them correctly. As in, like this:

```
>> msg from friend
                                                                             response from me ✓✓
>> msg from friend 2
                                                                             response from me ✓✓
```

**Comment by exquo** [comment] 2021-03-04 13:44
> Is this a feature or a bug?

Sounds like a bug to me. It should be the same as on signal-desktop (or any other messenger for that matter): the messages should be listed in chronological order.

One cause for this might be the system clock being out of sync. If the system clock is set to e.g. a year into the future, all the messages sent from that system would show up below any received messages. To check at what time scli thinks the messages are sent, you can check the Date field in the "info" box for any message: `tab` into the chat list, select a message under the cursor and press `i`.

**Comment by isamert** [comment] 2021-03-07 19:22
Seems like a system clock issue as @exquo pointed out. I went ahead changed my system clock and replicated the issue. One thing to note is that Signal's phone app handles this quite gracefully. I experimented with it and it seems like it's sorting the messages based on the time when the client received the message. Changing behavior to this should also fix the strange sorting problems I'm seeing time to time in scli (possibly other clients with out of sync clocks). I will look into fixing this.

**Comment by exquo** [comment] 2021-03-07 21:04
Yes, the official client is a bit smarter with handling messages from "the past". When it gets a new message with timestamp that's older than the last message, it puts the new message at the very bottom, below the "younger" (by timestamp) message, but shows the new message's timestamp as is. If a message is sent from a system whose time is a year into the past, the official client will report it to be from last year, but will still place it last.

**Comment by isamert** [comment] 2021-03-10 08:26
@jeanlucthumm Can you try the development branch? It should show the same timestamp with the signal desktop app now. (I haven't fixed the ordering issue yet, just fixed the timestamp. It was showing UTC time before, converted it to local time)

**Comment by exquo** [comment] 2021-03-10 10:04
@isamert, good call with local / UTC time difference, I think you're on to it!  

The https://github.com/isamert/scli/commit/914b91a0d36ea29e25f2a740cae867f3c5fcd85d probably isn't enough to solve the author's problem though: it only modifies how the time is shown in `MessageInfo`. To change the timestamp assigned to the sent message, we'll need to modify [this line](https://github.com/isamert/scli/blob/v0.4.0/scli#L1346):

```diff
-        ts = int(datetime.now().timestamp() * 1000)
+        ts = int(datetime.utcnow().timestamp() * 1000)
```

If we expect some back-and-forth on this, we might want to setlle it in a dedicated branch, like `hotfix/105`.

**Comment by exquo** [comment] 2021-03-10 10:16
I've opened a new issue #113 for the general question of how to handle messages with the "wrong" timestamps. Here let's solve the discrepancy of times reported in scli and in signal-desktop.

**Comment by exquo** [comment] 2021-03-31 16:12
@jeanlucthumm, are you still experiencing this issue? 

Sorry for a delay in following up on this! Disregard my comment about `utcnow()` above, the time-stamping should be good as is. The several hours difference between scli and signal-desktop was most likely caused by the timezone-aware datetime printing in message info, as @isamert had noted. This should not affect messages' ordering.

Could you please try again in a chat with two devices that have their clocks synced up?

**Comment by jeanlucthumm** [comment] 2021-04-02 02:19
Ok, I pulled from the repo again, and I chatted with a friend and the times seem to match the Signal desktop app. Also the message ordering issue went away. I'm not sure if this fix is from your end or a change in my environment, since I don't see any commits referencing this.

**Comment by exquo** [comment] 2021-04-02 12:04
Thanks for the update! The ordering issue was most likely fixed by syncing up the clocks on the devices. On one of them the time had probably been lagging behind, or set ahead into the future. There is still #113 to deal with those situations; we can close this one than.

**Closed by exquo** 2021-04-02 12:04 UTC
