### ISSUE TITLE
No contacts visible.

### ISSUE THREAD

**Issue by jhaggqvist** [isamert/scli#21] opened 2019-03-15 10:25 UTC
Followed README instructions, was able to link etc.
scli starts without any issues, However I can only see the groups I am part of but my contact list is completly empty.

Please let me know if you want logs or if I can assist in with something.

**Comment by isamert** [comment] 2019-03-15 10:53
Can you open the file `~/.local/share/signal-cli/data/PHONE_NUMBER` and look for the line that contains `"contactStore"`? It should contain your contact information like this:
```json
  "contactStore" : {
    "contacts" : [ {
      "name" : "...",
      "number" : "...",
      "color" : "light_green",
      "profileKey" : "..."
    }, {
      "name" : "...",
      "number" : "...",
      "color" : "green",
      "profileKey" : "..."
    }, {
    ...
```

If it's empty that means sync was unsuccessful. You can try these:
```sh
signal-cli -u PHONE_NUMBER updateAccount
signal-cli -u PHONE_NUMBER receive
```

Then check the file again. If `"contactStore"` is still empty it's an [signal-cli](https://github.com/AsamK/signal-cli) issue, and you can report it there.

If `"contactStore"` has some contact information but scli is still unable to show them, please post the contents of the `"contactStore"` (remove personal information before posting like `number`, `profileKey` etc. If they are empty or any other interesting features please note them.)

**Comment by jhaggqvist** [comment] 2019-03-18 06:57
Thank you for the quick reply and sorry for my slow reply.

I have gone through ~/.local/share/signal-cli/data/PHONE_NUMBER and there is nothing within contactStore and it does not seem to change after updateAccount and receive either.  

I will file an issue with signal-cli instead, thank you again for your quick and thorough response.

**Comment by cosmojg** [comment] 2019-06-07 20:11
Just thought I'd +1 this. I'm having this same exact issue on Arch Linux using scli-git, signal-cli, and libmatthew-unix-java from the AUR.

**Comment by cosmojg** [comment] 2019-06-07 21:11
After running `signal-cli -u PHONE_NUMBER updateAccount` and `signal-cli -u PHONE_NUMBER receive` multiple times, my contacts are showing up in scli, and I can send messages just fine. However, I can't receive messages properly. Messages appear at the bottom as `New message from NULL: "<insert message here>"`, and they don't appear in the message box for the relevant contact. Further, while my messages appear in the message box after sending, they disappear when I restart scli.

**Comment by isamert** [comment] 2019-06-07 21:47
> while my messages appear in the message box after sending, they disappear when I restart scli.

To enable history, start scli with `--save-history` or add `save-history=true` line to scli config.

> Messages appear at the bottom as New message from NULL: "<insert message here>", and they don't appear in the message box for the relevant contact

This happens when `signal-cli` receives messages without the contact number. I'm not sure what the cause is. Can you start scli with `--debug` and check the output of `~/.local/share/scli/log`. It probably contains lines like this: 
```
CRITICAL:root:NULL_CONTACT:{'source': '', 'sourceDevice': 1, 'relay': None, 'timestamp': ..., 'isReceipt': False, 'dataMessage': {'timestamp': ..., 'message': 'The message...', 'expiresInSeconds': 0, 'attachments': [], 'groupInfo': None}, 'syncMessage': None, 'callMessage': None}
```
The problem is `signal-cli` does not send the `source` field for some unknown reason and there is nothing I can do about this. If the `source` field is _not_ empty and you still see `New message from NULL:...` then it might be a scli issue.

**Comment by exquo** [comment] 2021-04-24 09:51
Seems like this has been an issue upstream which must have been been resolved since then. Feel free to reopen if reappears.

@0mp
On the [FreshPorts page](https://www.freshports.org/net-im/scli/) something similar is mentioned. Are you (or other BSD users) still experiencing this?

**Comment by 0mp** [comment] 2021-04-26 11:43
Yes, when I start scli it is always a hit or miss situation regarding the contact list. Sometimes, when I start scli I see my contact list for a brief moment only to see them disappear a second later.

**Comment by exquo** [comment] 2021-04-28 19:11
@0mp thanks for the update. I've assumed that comment on freshports was an old artefact, otherwise I'd try to help earlier! 

The contacts widgets list get updated when the signal-cli daemon has started (happens ~2 seconds after launching scli on my computer). At that point, scli pulls the contacts list again.

Can you check what's happening with the `contactStore` in signal-cli data file (see above) before and after the daemon starts? I.e. is there anything in that list before and after?

Also, this seems to be a bit different from the description on freshports: there it says that the contact list is empty _immediately_ after start, but can be populated with `:reload`. I guess that might be happening too, depending on when signal-cli modified the contacts list.

Other (general) things to try:
- run with `--debug`: there might be some hints there
- run with `--no-daemon`: to prevent signal-cli daemon from starting

**Comment by exquo** [comment] 2021-05-13 12:13
The problem should now be fixed in the upstream (see https://github.com/AsamK/signal-cli/issues/575#issuecomment-831453275). Feel free to re-open if the issue reappers.

**Closed by exquo** 2021-05-13 12:13 UTC
