### ISSUE TITLE
Contact names are forgotten

### ISSUE THREAD

**Issue by jbg** [isamert/scli#84] opened 2020-08-16 16:07 UTC
I use Signal without granting it access to my contacts.

Contacts in the left pane periodically lose their names and become phone numbers. Sometimes this happens at the moment of doing `:addContact` for a new contact (all contacts other than the one added lose their names and I have to subsequently `:renameContact` them), and sometimes it happens without an obvious trigger.

Also, when restarting `scli`, all entries in the left pane except my own phone number are lost. This would just be an inconvenience, except that when I receive a message from someone who has disappeared from the left pane, it doesn't recreate their entry and show me their message in the usual fashion, but rather just shows it at the bottom as `New message from NULL: "..."`

**Comment by exquo** [comment] 2020-08-16 21:23
I haven't tried not granting signal-android access to contacts on the phone, but I don't think it should make a difference. 

Does the second part of the issue (empty contact list, except your own number, on scli start) happen on every scli restart? Could you check if there are any entries in your signal-cli data file (`~/.local/share/signal-cli/data/+YOUR_PHONE_NUM`) under `groupStore` and `contactStore` before starting scli, then after starting and adding a contact there, and then after closing scli again?

**Comment by jbg** [comment] 2020-08-17 09:25
Before closing, I had four contacts with names in the left pane.

After closing, and before starting, `groupStore` is empty, and `contactStore` contains myself and one other contact (who has `name: null`).

After starting, the two phone numbers corresponding to the two contacts (one of which is myself; I won't mention the 'myself' contact below for brevity but it always remains there) that were in `contactStore` are shown in the left pane (no names). The `groupStore` and `contactStore` are unchanged at this point.

After performing `:renameContact +1234567890 Bob`, Bob is shown in the left pane, and the `contactStore` has updated to have this name. `groupStore` is unchanged.

After performing `:addContact +1999999999 Alice`, Bob has disappeared from the left pane, and been replaced with Alice. Bob has also disappeared from the `contactStore` and been replaced with an entry for Alice.

The file does not change when quitting.

I then launch again, and still the file does not change.

I then run `:addContact +1234567890 Bob` again, and now I have both Bob and Alice in the left pane, and in the `contactStore`.

I can now quit and relaunch repeatedly and the contacts both stay there. From prior experience it seems to be either the passage of time, or the receipt of a message, that will now cause one or both of them to disappear. I will report back.

**Comment by exquo** [comment] 2020-08-17 11:10
Thanks for the detailed response! 

I have followed the steps you have (very clearly) described, but could not reproduce on my side. I have even removed all groups and contacts except myself and another one with `name: null` from the signal-cli data file to make the conditions as similar as possible.
When the issue is supposed to occur
> After performing `:addContact +1999999999 Alice`, Bob has disappeared from the left pane, and been replaced with Alice

I get Alice and Bob side by side as expected. I do get the behavior you've described if I use the same phone number for both of them, i.e. `:addContact +1234567890 Alice`, but I understand that's not your case.

It's already a good thing though that you can reliably reproduce the issue, it would have been much harder to hunt down a sporadically occurring one. Some other things to consider in troubleshooting:
- Could the signal-cli's data file gotten corrupted somehow? Maybe try removing it and re-linking signal-cli to the master device again.
- Does `:reload` trigger the issue? This might be what's happening when this occurs sporadically.
- Is there any output in the scli's log file (`~/.local/share/scli/log`) if you run with `--debug` flag?

**Comment by jbg** [comment] 2020-08-18 09:39
On `:reload`, all contacts except one disappear, and the one remaining contact loses its name. I'm going to re-link soon, but I only just linked a few minutes before posting the original issue. I'll also check the logs.

**Comment by exquo** [comment] 2020-08-18 19:11
Okay good, so now we know that it's `:reload` that is causing the 'sporadic' part of the issue. Does running `:reload` also modify the signal-cli data file? Weird if it does, since AFAIK it's not supposed to call signal-cli at all.
If there is nothing interesting in the log messages, I can add some more debugging prints to make it more informative.

**Comment by exquo** [comment] 2020-09-12 12:09
@jbg are you still experiencing this issue? 

One other thing that would interfere with troubleshooting: be sure to disconnect your master device (phone) while experimenting with `rename`ing. I don't think that's what's causing the problems here, but it could complicate things by syncing / updating contacts list.

**Comment by exquo** [comment] 2020-09-18 13:36
Closing, could not reproduce.

**Closed by exquo** 2020-09-18 13:36 UTC
