### ISSUE TITLE
Crash on sending a message when searched contact

### ISSUE THREAD

**Issue by AckslD** [isamert/scli#101] opened 2021-01-20 08:59 UTC
If I search for a contact in the contact list and then send a message `scli` crashes with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/scli", line 2725, in <module>
    main()
  File "/usr/bin/scli", line 2721, in main
    loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/bin/scli", line 1935, in keypress
    key = super().keypress(size, key)
  File "/usr/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.9/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.9/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3.9/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/bin/scli", line 1749, in keypress
    self.state.signal.send_message(self.state.current_contact, txt)
  File "/usr/bin/scli", line 1255, in send_message
    urwid.emit_signal(self, 'send_message', envelope)
  File "/usr/lib/python3.9/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.9/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/bin/scli", line 1385, in on_new_message
    self.move_contact_top(contact_widget)
  File "/usr/bin/scli", line 1412, in move_contact_top
    self.focus_position = offset
  File "/usr/lib/python3.9/site-packages/urwid/listbox.py", line 550, in set_focus
    self._body.set_focus(position)
  File "/usr/lib/python3.9/site-packages/urwid/listbox.py", line 203, in set_focus
    self.focus = position
  File "/usr/lib/python3.9/site-packages/urwid/monitored_list.py", line 165, in _set_focus
    raise IndexError('focus index is out of range: %s' % (index,))
IndexError: focus index is out of range: 9 
```

I am using the AUR package with version `r185.9695ce1-1`

**Comment by exquo** [comment] 2021-01-20 09:24
Can't reproduce yet. I'm following these steps:

- search in contacts list with `/`
- select one of the contacts with `Enter`
- send a message to that contact

Everything seems to be working okay.

Also, I don't know how AUR versions things. On its [page](https://aur.archlinux.org/packages/scli-git/) it currently says: Package Details: scli-git r11.faf5ca2-1

Could you try with `master`, `develop` or the latest release?

**Comment by AckslD** [comment] 2021-01-20 09:31
Thanks for your reply @exquo! It seems to happen when I have `--group-contacts`. Are you able to reproduce it then? If not I'll try out from the branches directly.

**Comment by exquo** [comment] 2021-01-20 10:29
Thanks for the clarification! I can now reproduce it with `--group-contacts` and sending to individual contact. Will look at this soon.

**Comment by exquo** [comment] 2021-01-20 11:59
Now fixed in `develop`.

**Comment by AckslD** [comment] 2021-01-20 12:08
@exquo Cool! I'm wondering, wouldn't it be good to have some `try/catch` for these things. I would say it's better to just be notified of the error if something like this happens, rather than the whole session crashing and the message that one wrote gets lost. What do you think?

**Comment by exquo** [comment] 2021-01-20 12:33
In one sense - absolutely! Anything that causes crashes from an uncaught exception is a wicked bug. But in general `try/except` shouldn't be used as a catchall trap. While we could wrap the whole program in

```python
try:
    main()
except:
    <notify the user of the error>
```

and it might save us some embarrassment from crashes, the real problem is: something unpredictable has happened and the program might have gotten in a state that should have never been reached. This can even lead to data corruption (e.g. while saving conversations history). So after this happens the program should really quit and complain. And so should the users :)

When we write `try / except` we should already know what kind of problem we are anticipating. If we have failed to anticipate it - well, that's what the issue tracker is for!

**Comment by AckslD** [comment] 2021-01-20 12:46
Makes a lot of sense @exquo :)

**Closed** 2021-01-21 12:27 UTC
